### ISSUE TITLE
No Portal Found

### ISSUE THREAD

**Issue by Craigdb** [cppchriscpp/TravelPortals#20]
I was trying your portal plugin as a replacement for runecraft teleporters. Using Spigot for MC 1.13.1
I can create a portal and it reports back OK - the yml file shows a portal and co-ords etc correctly (mind you, when I make another one the old one breaks and the yml only shows 1 portal but with the new coords.) Once created I use the '/portal name test' command but it reports back:

No portal found! (You must be within one block of the portal.)

Obviously, I made sure I was within one block, even tested inside the water area. Similar message when using /portal info. Any suggestions for this appreciated,

**Comment by cppchriscpp** [comment]
Sorry for the lack of reply; I'm having a hard time finding time for this plugin right now. I can reproduce the problem - something seems quite off. I'm not quite sure what is causing this yet though. 

```
Spigot version: git-Spigot-f6a273b-7
a2f486 (MC: 1.13.1) (Implementing API version 1.13.1-R0.1-SNAPSHOT)
Minecraft client version: 1.13.1
Travelportals version: TravelPortals 2.4 (1.13 dev build 9)
```

I was also able to reproduce it with the Craftbukkit jar: `git-Bukkit-7a2f486 (
MC: 1.13.1) (Implementing API version 1.13.1-R0.1-SNAPSHOT)`

The game seems to only ever recognize the most recently created portal (As Craigdb noted) - if I create a portal then break a block on it, I get the portal destroyed message. If I create two portals, I can break the first one without a message, but the second one breaks as expected. (However, I can't use any of the portal commands no matter where I am in relation to the portal.)

It is also reproducible going back to 1.13 with spigot `git-Spigot-fe3ab0d-1
62bda9 (MC: 1.13) (Implementing API version 1.13-R0.1-SNAPSHOT)`

Afraid I don't have any suggested workaround beyond sticking with an older build for now.

**Comment by cppchriscpp** [comment]
It looks like there are two separate problems here: 
1. Due to storing portals using their name as a key, you can only have one nameless portal on a server at a time. This by itself would be annoying, but not huge, but the second problem is
2. We're no longer recognizing when the player steps into a portal.

I'm still digging into the cause behind that second issue.

**Comment by cppchriscpp** [comment]
I think I've found it! The problem seems to be here: 

https://github.com/cppchriscpp/TravelPortals/blob/master/src/main/java/net/cpprograms/minecraft/TravelPortals/storage/PortalStorage.java#L79

I think this should read: 
```java
        String portalName = portalLocations.get(location.getWorld().getName() + "," + location.getBlockX() + "," + location.getBlockY() + "," + location.getBlockZ());
```

The problem seems to be that we're looking up portals based on something other than the world name. (Perhaps the `World` class used to have a `getString()` that returned its name, and now doesn't? I didn't look...) 

I'm not going to be able to put anything together tonight, and tomorrow's unfortunately completely booked. I'll try to get something out for this soon though.

**Comment by cppchriscpp** [comment]
I got a fix to this together. It's going to take a little longer to get an official release out, but for now I've attached a new jar that should solve the problems you described. (Please reply back if it doesn't!) 

The official fix is in pr #21 

[TravelPortals_2.4_fixes.zip](https://github.com/cppchriscpp/TravelPortals/files/2448481/TravelPortals_2.4_fixes.zip)

**Comment by Craigdb** [comment]
I tested it and seem to be getting the same reults.

**Comment by Craigdb** [comment]
Here is the config. FYI I have downloaded the latest spigot 1.13 and
deleted the old portal.jar and deleted the plugin folder so it would
re-create from scratch. Same end result.

**Comment by Craigdb** [comment]
Sorry about the delays - I have not been well. Anyway - I just re-ran build
tools for the latest spigot and ran TP build #11 and I am still getting the
same result.

**Comment by Phoenix616** [comment]
The possible reasons why this occurred should now be fixed as far as I can tell:

- Not close enough to portal - Try looking into the portal instead of standing in it as that might lead to better results (56a2047e0e1def780d1b7a88a9f1eeaf946b1f3f)
- Fixed a but where two portals at the same location would override each other, that way a portal that had a way could be overwritten by another one without the name (could happen due to how old saving/importing works) (145472d6ccd6e0f68fa0642533e6723f35cd0fd1 works around that case)
- Portal storage doesn't use name to identify portals anymore so that multiple non-named portals can exist (f307384b2c2b0bf37bf7cb833dea867ed516916b)

If this is still happening for someone then please comment here or open a new issue with some more information (ideally your config and storage file(s))

**Comment by Phoenix616** [comment]
Found another bug that could lead to this issue which is fixed with 826212c6e0712cef8a1998b07548b2d4294c769e: The radius search basically used the wrong coordinates after the loop was completed once.
